# Generated by Django 2.1.3 on 2018-11-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0005_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='rank',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='hacathon.Task'),
        ),
    ]
