# Generated by Django 2.1.3 on 2018-11-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0007_auto_20181111_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='levelup_points',
            field=models.IntegerField(default=0),
        ),
    ]
