# Generated by Django 2.1.3 on 2018-11-10 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0008_customer_levelup_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 11, 4, 18, 22, 154630))),
                ('payment', models.CharField(max_length=255)),
            ],
        ),
    ]
