# Generated by Django 2.1.3 on 2018-11-11 01:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0011_auto_20181111_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_card', models.CharField(max_length=255)),
                ('digits', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hacathon.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 11, 7, 36, 8, 355338)),
        ),
    ]
