# Generated by Django 2.1.3 on 2018-11-11 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0012_auto_20181111_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('summa', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hacathon.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='onai',
            name='customer',
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 11, 10, 51, 55, 904785)),
        ),
        migrations.DeleteModel(
            name='Onai',
        ),
    ]
