# Generated by Django 2.1.3 on 2018-11-11 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0013_auto_20181111_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='month',
            new_name='expiration',
        ),
        migrations.RemoveField(
            model_name='card',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='card',
            name='summa',
        ),
        migrations.RemoveField(
            model_name='card',
            name='year',
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 11, 11, 4, 8, 625694)),
        ),
    ]
