# Generated by Django 2.1.3 on 2018-11-11 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0014_auto_20181111_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 11, 11, 14, 8, 183987)),
        ),
    ]
