# Generated by Django 2.1.3 on 2018-11-11 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacathon', '0015_auto_20181111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 11, 11, 11, 23, 9, 49923)),
        ),
    ]
